### ISSUE TITLE
Archive post image size change looks strange

### ISSUE THREAD

**Issue by josswright** [s56bouya/nishiki#25]
I recently noticed that the images on my blog's main page 'read more' links had stopped being the full width of the 'read more' div. It looks like this change was deliberate in commit 017b357c1b862ce419d988c792db2811db09f50d 

It looks like the thumbnails are too small for this use. Is there a way to use a larger size?

**Comment by s56bouya** [comment]
Hi.
I changed the aspect ratio of the image of the archive page since it looks beautiful at "16: 9". Create images If the thumbnail size got smaller, resize thumbnails using the Regenerate Thumbnails plugin. The recommended size is 640 × 360 pixels.

・Regenerate Thumbnails
https://wordpress.org/plugins/regenerate-thumbnails/

**Comment by josswright** [comment]
Ah, that's really helpful. I'll fix my thumbnails. Thank you!

(EDIT: You're right -- it looks much better at 16:9!)

**Comment by s56bouya** [comment]
Great! Thanks for letting us know. 

Best wishes.
