### ISSUE TITLE
Featured images turned into thumbnails

### ISSUE THREAD

**Issue by rayito** [s56bouya/nishiki#26]
With the latest version, the full-width featured images in the posts page and category pages turned into tiny, 150x150px thumbnails.

**Comment by s56bouya** [comment]
Hi.
I changed the aspect ratio of the image of the archive page since it looks beautiful at "16: 9". Create images If the thumbnail size got smaller, resize thumbnails using the Regenerate Thumbnails plugin. The recommended size is 640 × 360 pixels.

Please refer to a similar issue and solve it.
#25
